# Generated by Django 3.2 on 2022-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Customers/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'manager'), ('S', 'seller'), ('C', 'customer')], max_length=20, verbose_name='Должность'),
        ),
    ]
